### ISSUE TITLE
Research proposal format

### ISSUE THREAD

**Issue by Powetm** [STT2810-SP15/DiscussionSTT2810#5]
How is the research proposal suppose to be structured? (html format?) And is the entire 4-5 page project due this Friday Feb. 6, 2015?

**Comment by alanarnholt** [comment]
Please structure exactly like the book example.  The book example is reproduced in the class repo with an *Rmd file.  You will submit the resulting *.html file for grading.  The example can be found at https://github.com/STT2810-SP15/STT2810ClassRepoSP15/blob/master/ResearchProposal/ResearchProposal.Rmd

One little note....the book says 4-5 pages double spaced...but your document should be roughly 2-2.5 since it will not be double spaced.

**Comment by alanarnholt** [comment]
Yes...the research proposal is due 2/6/15 NLT 5pm
